-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.7.2-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for vu2
CREATE DATABASE IF NOT EXISTS `vu2` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `vu2`;

-- Dumping structure for table vu2.hibernate_sequence
CREATE TABLE IF NOT EXISTS `hibernate_sequence` (
  `next_val` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.hibernate_sequence: ~1 rows (approximately)
/*!40000 ALTER TABLE `hibernate_sequence` DISABLE KEYS */;
INSERT INTO `hibernate_sequence` (`next_val`) VALUES
	(9);
/*!40000 ALTER TABLE `hibernate_sequence` ENABLE KEYS */;

-- Dumping structure for table vu2.moviedata
CREATE TABLE IF NOT EXISTS `moviedata` (
  `id` bigint(20) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `genre` varchar(255) DEFAULT NULL,
  `imdb_id` varchar(255) DEFAULT NULL,
  `poster_link` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `trailer_link` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.moviedata: ~187 rows (approximately)
/*!40000 ALTER TABLE `moviedata` DISABLE KEYS */;
INSERT INTO `moviedata` (`id`, `description`, `genre`, `imdb_id`, `poster_link`, `title`, `trailer_link`, `year`) VALUES
	(101, 'With his debts mounting and angry collectors closing in, a fast-talking New York City jeweler risks everything in hope of staying afloat and alive.', 'drama', 'tt5727208', 'https://m.media-amazon.com/images/M/MV5BZDhkMjUyYjItYWVkYi00YTM5LWE4MGEtY2FlMjA3OThlYmZhXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg', 'Uncut Gems', 'https://www.youtube.com/embed/vTfJp2Ts9X8', '2019'),
	(102, 'A family of South Korean immigrants tries to make it in the U.S. during the 1980s.', 'drama', 'tt10633456', 'https://m.media-amazon.com/images/M/MV5BNWEzOTNjNDgtZDhhYS00ODAxLWIzNGMtYjU3OGZhYmI3ZDU4XkEyXkFqcGdeQXVyMTAzNjk5MDI4._V1_SX300.jpg', 'Minari', 'https://www.youtube.com/embed/KQ0gFidlro8', '2020'),
	(103, 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'thriller', 'tt6751668', 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg', 'Parasite', 'https://www.youtube.com/embed/5xH0HfJHsaY', '2019'),
	(104, 'A Scottish lord becomes convinced by a trio of witches that he will become the next King of Scotland, and his ambitious wife supports him in his plans of seizing power.', 'thriller', 'tt10095582', 'https://m.media-amazon.com/images/M/MV5BMzM0YWNmMDEtNmI3Yy00NjQ4LWJlZjMtMzk2YjUxOThhZGQxXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg', 'The Tragedy of Macbeth', 'https://www.youtube.com/embed/HM3hsVrBMA4', '2021'),
	(105, 'Four college girls hold up a restaurant in order to fund their spring break vacation. While partying, drinking, and taking drugs, they are arrested, only to be bailed out by a drug and arms dealer.', 'drama', 'tt2101441', 'https://m.media-amazon.com/images/M/MV5BNDBmYjU3NzAtZGVkNS00N2E3LWEyNTgtMjIwMTczYTE0M2Y4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Spring Breakers', 'https://www.youtube.com/embed/imDML4om8z8', '2013'),
	(106, 'Set on the east coast in northern Scotland, it traces an extraterrestrial who, manifesting in human form, drives around the countryside picking up male hitchhikers whom she drugs and delivers to her home planet.', 'sci-fi', 'tt1441395', 'https://m.media-amazon.com/images/M/MV5BMTU1MDEwMDg4Nl5BMl5BanBnXkFtZTgwOTk3NTcxMTE@._V1_SX300.jpg', 'Under the Skin', 'https://www.youtube.com/embed/7S1yhSp5jaI', '2013'),
	(107, 'A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.', 'sci-fi', 'tt0470752', 'https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_SX300.jpg', 'Ex Machina', 'https://www.youtube.com/embed/bggUmgeMCdc', '2014'),
	(108, 'A punk rock band is forced to fight for survival after witnessing a murder at a neo-Nazi skinhead bar.', 'thriller', 'tt4062536', 'https://m.media-amazon.com/images/M/MV5BMjU1ODQ5NzA0N15BMl5BanBnXkFtZTgwMDg5MTA5NzE@._V1_SX300.jpg', 'Green Room', 'https://www.youtube.com/embed/yKdVYUXyBzU', '2015'),
	(109, 'After a botched bank robbery lands his younger brother in prison, Connie Nikas embarks on a twisted odyssey through New York City\'s underworld to get his brother Nick out of jail.', 'thriller', 'tt4846232', 'https://m.media-amazon.com/images/M/MV5BNGQ3Y2VjNmUtMDdiMC00YTE1LWI5NmUtZDIzMTJmODQyNDU4XkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg', 'Good Time', 'https://www.youtube.com/embed/AVyGCxHZ_Ko', '2017'),
	(110, 'A minister of a small congregation in upstate New York grapples with mounting despair brought on by tragedy, worldly concerns and a tormented past.', 'drama', 'tt6053438', 'https://m.media-amazon.com/images/M/MV5BZDI1MGIyZDMtYjAyMy00ZWE1LTgzYjctYzM5MzczNjFjZWQwXkEyXkFqcGdeQXVyODQyNzE3MDg@._V1_SX300.jpg', 'First Reformed', 'https://www.youtube.com/embed/hCF5Y8dQpR4', '2017'),
	(111, 'French dancers gather in a remote, empty school building to rehearse on a wintry night. The all-night celebration morphs into a hallucinatory nightmare when they learn their sangria is laced with LSD.', 'horror', 'tt8359848', 'https://m.media-amazon.com/images/M/MV5BMjllYmQ2OGQtN2IxZC00ODJiLWI4NjQtYmNlZjYzNzUzYjkyXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg', 'Climax', 'https://www.youtube.com/embed/Hi69nL_VrTE', '2018'),
	(112, 'A couple\'s first date takes an unexpected turn when a police officer pulls them over.', 'drama', 'tt8722346', 'https://m.media-amazon.com/images/M/MV5BMjIzYmJkZmEtM2RkZS00MDA4LTg4NjAtOGRkN2EwZmFmMWE4XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg', 'Queen & Slim', 'https://www.youtube.com/embed/JW4RgX08xXw', '2019'),
	(113, 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.', 'romance', 'tt0338013', 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg', 'Eternal Sunshine of the Spotless Mind', 'https://www.youtube.com/embed/07-QBnEkgXU', '2004'),
	(114, 'While homesick in bed, a young boy\'s grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.', 'romance', 'tt0093779', 'https://m.media-amazon.com/images/M/MV5BMGM4M2Q5N2MtNThkZS00NTc1LTk1NTItNWEyZjJjNDRmNDk5XkEyXkFqcGdeQXVyMjA0MDQ0Mjc@._V1_SX300.jpg', 'The Princess Bride', 'https://www.youtube.com/embed/P9FRDyTerZA', '1987'),
	(115, 'Shakespeare\'s famous play is updated to the hip modern suburb of Verona still retaining its original dialogue.', 'romance', 'tt0117509', 'https://m.media-amazon.com/images/M/MV5BMGU4YmI1ZGQtZjExYi00M2E0LTgyYTAtNzQ5ZmVlMTk4NzUzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Romeo + Juliet', 'https://www.youtube.com/embed/8VOAxzgq42A', '1996'),
	(116, 'Tragedy strikes a married couple on vacation in the Moroccan desert, touching off an interlocking story involving four different families spanning the globe.', 'drama', 'tt0449467', 'https://m.media-amazon.com/images/M/MV5BYTJkZDljNGYtNjRiNC00ZmY2LTg1NmItYTI1MTllNDQzMWVmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Babel', 'https://www.youtube.com/embed/yDNa6t-TDrQ', '2006'),
	(117, 'The relationship of a contemporary married couple, charting their evolution over a span of years by cross-cutting between time periods.', 'drama', 'tt1120985', 'https://m.media-amazon.com/images/M/MV5BMTU4MTQ2MzA1Ml5BMl5BanBnXkFtZTcwODE3NTgwNA@@._V1_SX300.jpg', 'Blue Valentine', 'https://www.youtube.com/embed/gd1uBiV31SU', '2010'),
	(119, 'A grieving family is haunted by tragic and disturbing occurrences.', 'horror', 'tt7784604', 'https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg', 'Hereditary', 'https://www.youtube.com/embed/MJNR58zaStE', '2018'),
	(120, 'A couple travels to Northern Europe to visit a rural hometown\'s fabled Swedish mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.', 'horror', 'tt8772262', 'https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_SX300.jpg', 'Midsommar', 'https://www.youtube.com/embed/1Vnghdsjmd0', '2019'),
	(121, 'After returning to his childhood home, a disgraced children\'s puppeteer is forced to confront his wicked stepfather and the secrets that have tortured his entire life.', 'horror', 'tt6081670', 'https://m.media-amazon.com/images/M/MV5BNGQ1MGFjNmQtZGVlOC00NTY4LTgwZGItYjcyYWI2MTU4ZWE5XkEyXkFqcGdeQXVyNzYwNzAxMjM@._V1_SX300.jpg', 'Possum', 'https://www.youtube.com/embed/O5jaqmQyAJw', '2018'),
	(122, 'Four weeks after a mysterious, incurable virus spreads throughout the UK, a handful of survivors try to find sanctuary.', 'horror', 'tt0289043', 'https://m.media-amazon.com/images/M/MV5BYTFkM2ViMmQtZmI5NS00MjQ2LWEyN2EtMTI1ZmNlZDU3MTZjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', '28 Days Later', 'https://www.youtube.com/embed/7suz9ndPBHg', '2002'),
	(123, 'Travis Henderson, an aimless drifter who has been missing for four years, wanders out of the desert and must reconnect with society, himself, his life, and his family.', 'drama', 'tt0087884', 'https://m.media-amazon.com/images/M/MV5BM2RjMmU3ZWItYzBlMy00ZmJkLWE5YzgtNTVkODdhOWM3NGZhXkEyXkFqcGdeQXVyNDA5Mjg5MjA@._V1_SX300.jpg', 'Paris, Texas', 'https://www.youtube.com/embed/9e590FeeGCM', '1984'),
	(124, 'Secure within a desolate home as an unnatural threat terrorizes the world, a man has established a tenuous domestic order with his wife and son. Then a desperate young family arrives seeking refuge.', 'horror', 'tt4695012', 'https://m.media-amazon.com/images/M/MV5BMjQ3MDA0ODA2N15BMl5BanBnXkFtZTgwNzg0NzgwMjI@._V1_SX300.jpg', 'It Comes At Night', 'https://www.youtube.com/embed/6YOYHCBQn9g', '2017'),
	(125, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.', 'drama', 'tt4975722', 'https://m.media-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg', 'Moonlight', 'https://www.youtube.com/embed/9NJj12tJzqc', '2016'),
	(126, 'A young man searches for home in the changing city that seems to have left him behind.', 'drama', 'tt4353250', 'https://m.media-amazon.com/images/M/MV5BNTQ5OTUwYjQtYmM5Ni00YTY5LWFiOWEtYTg1MTg2Y2NmY2JhXkEyXkFqcGdeQXVyMTAzNjk5MDI4._V1_SX300.jpg', 'The Last Black Man in San Francisco', 'https://www.youtube.com/embed/C0FnJDhY9-0', '2019'),
	(127, 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; \'Rosebud\'.', 'classic', 'tt0033467', 'https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Citizen Kane', 'https://www.youtube.com/embed/qg0j--Kxf0I', '1941'),
	(128, 'Young Dorothy Gale and her dog are swept away by a tornado from their Kansas farm to the magical Land of Oz, and embark on a quest with three new friends to see the Wizard, who can return her to her home and fulfill the others\' wishes.', 'classic', 'tt0032138', 'https://m.media-amazon.com/images/M/MV5BNjUyMTc4MDExMV5BMl5BanBnXkFtZTgwNDg0NDIwMjE@._V1_SX300.jpg', 'The Wizard of Oz', 'https://www.youtube.com/embed/FfpF8UUVTeM', '1939'),
	(129, 'A wheelchair-bound photographer spies on his neighbors from his Greenwich Village courtyard apartment window, and becomes convinced one of them has committed murder, despite the skepticism of his fashion-model girlfriend.', 'classic', 'tt0047396', 'https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Rear Window', 'https://www.youtube.com/embed/m01YktiEZCw', '1954'),
	(130, 'A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.', 'classic', 'tt0045152', 'https://m.media-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'Singin\' in the Rain', 'https://www.youtube.com/embed/lSE8sl2-PZg', '1952'),
	(131, 'A German youth eagerly enters World War I, but his enthusiasm wanes as he gets a firsthand view of the horror.', 'classic', 'tt0020629', 'https://m.media-amazon.com/images/M/MV5BMzg2MWQ4MDEtOGZlNi00MTg0LWIwMjQtYWY5NTQwYmUzMWNmXkEyXkFqcGdeQXVyMzg2MzE2OTE@._V1_SX300.jpg', 'All Quiet on the Western Front', 'https://www.youtube.com/embed/grapXipP3fM', '1930'),
	(132, 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.', 'drama', 'tt0469494', 'https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg', 'There Will Be Blood', 'https://www.youtube.com/embed/0FIm5ATyAY0', '2007'),
	(133, 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.', 'classic', 'tt0034583', 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'Casablanca', 'https://www.youtube.com/embed/S9ID5DHsX8g', '1942'),
	(134, '"A newspaper editor uses every trick in the book to keep his ace reporter ex-wife from remarrying.', 'classic', 'tt0032599', 'https://m.media-amazon.com/images/M/MV5BZDVmZTZkYjMtNmViZC00ODEzLTgwNDAtNmQ3OGQwOWY5YjFmXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg', 'His Girl Friday', 'https://www.youtube.com/embed/0GYX46Bs1_8', '1940'),
	(135, 'In a futuristic city sharply divided between the working class and the city planners, the son of the city\'s mastermind falls in love with a working-class prophet who predicts the coming of a savior to mediate their differences.', 'classic', 'tt0017136', 'https://m.media-amazon.com/images/M/MV5BMTg5YWIyMWUtZDY5My00Zjc1LTljOTctYmI0MWRmY2M2NmRkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Metropolis', 'https://www.youtube.com/embed/gdtZv3XROnc', '1927'),
	(136, 'Three friends struggle to find work in Paris. Things become more complicated when two of them fall in love with the same woman.', 'classic', 'tt0043278', 'https://m.media-amazon.com/images/M/MV5BMzFkNGM0YTUtZjY5Ny00NzBkLWE1NTAtYzUxNjUyZmJlODMwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'An American In Paris', 'https://www.youtube.com/embed/1XMXAleA1eQ', '1951'),
	(137, 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.', 'classic', 'tt0053125', 'https://m.media-amazon.com/images/M/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'North by Northwest', 'https://www.youtube.com/embed/ek7T9Gyl_J4', '1959'),
	(138, 'A film crew goes to a tropical island for an exotic location shoot and discovers a colossal ape who takes a shine to their female blonde star. He is then captured and brought back to New York City for public exhibition.', 'classic', 'tt0024216', 'https://m.media-amazon.com/images/M/MV5BZTY3YjYxZGQtMTM2YS00ZmYwLWFlM2QtOWFlMTU1NTAyZDQ2XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg', 'King Kong', 'https://www.youtube.com/embed/PbrikL8IjXM', '1933'),
	(139, 'Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter\'s wife.', 'classic', 'tt0013442', 'https://m.media-amazon.com/images/M/MV5BMTAxYjEyMTctZTg3Ni00MGZmLWIxMmMtOGM2NTFiY2U3MmExXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Nosferatu, a Symphony of Horror', 'https://www.youtube.com/embed/npxhdRMYHy0', '1922'),
	(140, 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', 'classic', 'tt0054215', 'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Psycho', 'https://www.youtube.com/embed/Wz719b9QUqY', '1960'),
	(141, 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors in occupied Burma, not knowing that the allied forces are planning a daring commando raid through the jungle to destroy it.', 'classic', 'tt0050212', 'https://m.media-amazon.com/images/M/MV5BOGY5NmNlMmQtYzRlYy00NGQ5LWFkYjYtNzExZmQyMTg0ZDA0XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg', 'The Bridge on the River Kwai', 'https://www.youtube.com/embed/RlC7XBayj0s', '1957'),
	(142, 'Mary Shelley reveals the main characters of her novel survived: Dr. Frankenstein, goaded by an even madder scientist, builds his monster a mate.', 'classic', 'tt0026138', 'https://m.media-amazon.com/images/M/MV5BOTUzMzAzMzEzNV5BMl5BanBnXkFtZTgwOTg1NTAwMjE@._V1_SX300.jpg', 'The Bride of Frankenstein', 'https://www.youtube.com/embed/rYD3-pIF9jQ', '1935'),
	(143, 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', 'classic', 'tt0050083', 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', '12 Angry Men', 'https://www.youtube.com/embed/2L4IhbF2WK0', '1957'),
	(144, 'A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.', 'classic', 'tt0071315', 'https://m.media-amazon.com/images/M/MV5BOGMwYmY5ZmEtMzY1Yi00OWJiLTk1Y2MtMzI2MjBhYmZkNTQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Chinatown', 'https://www.youtube.com/embed/Z70axRwP74Q', '1974'),
	(145, 'Disturbed Blanche DuBois moves in with her sister in New Orleans and is tormented by her brutish brother-in-law while her reality crumbles around her.', 'classic', 'tt0044081', 'https://m.media-amazon.com/images/M/MV5BNzk2M2Y3MzYtNGMzMi00Y2FjLTkwODQtNmExYWU3ZWY3NzExXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'A Streetcar Named Desire', 'https://www.youtube.com/embed/FVDecBMyyZI', '1951'),
	(146, 'The assault of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai\'s ghost and a woodcutter.', 'classic', 'tt0042876', 'https://m.media-amazon.com/images/M/MV5BMjEzMzA4NDE2OF5BMl5BanBnXkFtZTcwNTc5MDI2NQ@@._V1_SX300.jpg', 'Rashomon', 'https://www.youtube.com/embed/xCZ9TguVOIA', '1951'),
	(147, 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.', 'classic', 'tt0038650', 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg', 'It\'s a Wonderful Life', 'https://www.youtube.com/embed/iLR3gZrU2Xo', '1946'),
	(148, 'A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.', 'classic', 'tt0052357', 'https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'Vertigo', 'https://www.youtube.com/embed/95o-QM-lz8g', '1958'),
	(149, 'An Oklahoma family driven off their farm by the poverty and hopelessness of the Dust Bowl joins the westward migration to California, suffering the misfortunes of the homeless in the Great Depression.', 'classic', 'tt0032551', 'https://m.media-amazon.com/images/M/MV5BNzJiOGI2MjctYjUyMS00ZjkzLWE2ZmUtOTg4NTZkOTNhZDc1L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'The Grapes of Wrath', 'https://www.youtube.com/embed/fOuAZLA_jWQ', '1940'),
	(150, 'Private detective Philip Marlowe is hired by a wealthy family. Before the complex case is over, he\'s seen murder, blackmail, and what might be love.', 'classic', 'tt0038355', 'https://m.media-amazon.com/images/M/MV5BMjdiM2IyZmQtODJiYy00NDNkLTllYmItMmFjMDNiYTQyOGVkXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg', 'The Big Sleep', 'https://www.youtube.com/embed/n-K49CUaeto', '1946'),
	(151, 'A laid back Southern man is sentenced to two years in a rural prison, but refuses to conform.', 'classic', 'tt0061512', 'https://m.media-amazon.com/images/M/MV5BOWFlNzZhYmYtYTI5YS00MDQyLWIyNTUtNTRjMWUwNTEzNjA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg', 'Cool Hand Luke', 'https://www.youtube.com/embed/ofxtDrRVQY4', '1967'),
	(152, 'The Monoliths push humanity to reach for the stars; after their discovery in Africa generations ago, the mysterious objects lead mankind on an awesome journey to Jupiter, with the help of H.A.L. 9000: the world\'s greatest supercomputer.', 'sci-fi', 'tt0062622', 'https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', '2001: A Space Odyssey', 'https://www.youtube.com/embed/oR_e9y-bka0', '1967'),
	(153, 'A pious nurse becomes dangerously obsessed with saving the soul of her dying patient.', 'horror', 'tt7557108', 'https://m.media-amazon.com/images/M/MV5BYzE3ZDg0OTktYjlhNC00ZmQ0LTk0YjktMDE1ZWE2YjIwMjk4XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg', 'Saint Maud', 'https://www.youtube.com/embed/EXs2-TY9qok', '2019'),
	(154, 'A young couple trying for a baby move into an aging, ornate apartment building on Central Park West, but find themselves surrounded by peculiar neighbors.', 'horror', 'tt0063522', 'https://m.media-amazon.com/images/M/MV5BZmEwZGU2NzctYzlmNi00MGJkLWE3N2MtYjBlN2ZhMGJkZTZiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Rosemary\'s Baby', 'https://www.youtube.com/embed/dBSbmNNm84Y', '1968'),
	(155, 'The manipulative daughter of a Georgia plantation owner conducts a turbulent romance with a roguish profiteer during the American Civil War and Reconstruction periods.', 'classic', 'tt0031381', 'https://m.media-amazon.com/images/M/MV5BYjUyZWZkM2UtMzYxYy00ZmQ3LWFmZTQtOGE2YjBkNjA3YWZlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Gone With the Wind', 'https://www.youtube.com/embed/h2oX0zQA67U', '1939'),
	(157, 'An American POW in the Korean War is brainwashed as an unwitting assassin for an international Communist conspiracy.', 'classic', 'tt0056218', 'https://m.media-amazon.com/images/M/MV5BOTY0ZTA1ZjUtN2MyNi00ZGRmLWExYmMtOTkyNzI1NGQ2Y2RlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'The Manchurian Candidate', 'https://www.youtube.com/embed/Oc8LpuM5Bhs', '1962'),
	(158, 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.', 'classic', 'tt0073486', 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'One Flew Over the Cuckoo\'s Nest', 'https://www.youtube.com/embed/_A4bCifObI4', '1975'),
	(159, 'A family\'s serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.', 'horror', 'tt6857112', 'https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg', 'Us', 'https://www.youtube.com/embed/hNCmb-4oXJA', '2019'),
	(160, 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.', 'horror', 'tt5052448', 'https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg', 'Get Out', 'https://www.youtube.com/embed/DzfpyUB60YY', '2017'),
	(161, 'A single mother and her child fall into a deep well of paranoia when an eerie children\'s book titled "Mister Babadook" manifests in their home.', 'horror', 'tt2321549', 'https://m.media-amazon.com/images/M/MV5BMTk0NzMzODc2NF5BMl5BanBnXkFtZTgwOTYzNTM1MzE@._V1_SX300.jpg', 'The Babadook', 'https://www.youtube.com/embed/yPYFwJJgKuI', '2014'),
	(162, 'Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.', 'horror', 'tt7984734', 'https://m.media-amazon.com/images/M/MV5BZmE0MGJhNmYtOWNjYi00Njc5LWE2YjEtMWMxZTVmODUwMmMxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'The Lighthouse', 'https://www.youtube.com/embed/Hyag7lR8CPA', '2019'),
	(163, 'A young woman is followed by an unknown supernatural force after a sexual encounter.', 'horror', 'tt3235888', 'https://m.media-amazon.com/images/M/MV5BMmU0MjBlYzYtZWY0MC00MjliLWI3ZmUtMzhlZDVjMWVmYWY4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'It Follows', 'https://www.youtube.com/embed/HkZYbOH0ujw', '2015'),
	(164, 'Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.', 'horror', 'tt0077651', 'https://m.media-amazon.com/images/M/MV5BNzk1OGU2NmMtNTdhZC00NjdlLWE5YTMtZTQ0MGExZTQzOGQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Halloween', 'https://www.youtube.com/embed/oVgtguYmNBg', '1978'),
	(165, 'A ragtag group of Pennsylvanians barricade themselves in an old farmhouse to remain safe from a horde of flesh-eating ghouls that are ravaging the East Coast of the United States.', 'horror', 'tt0063350', 'https://m.media-amazon.com/images/M/MV5BMzRmN2E1ZDUtZDc2ZC00ZmI3LTkwOTctNzE2ZDIzMGJiMTYzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Night of the Living Dead', 'https://www.youtube.com/embed/V5XwrRFP7Zw', '1968'),
	(166, 'A monster emerges from Seoul\'s Han River and begins attacking people. One victim\'s loving family does what it can to rescue her from its clutches.', 'horror', 'tt0468492', 'https://m.media-amazon.com/images/M/MV5BMTE3N2IwNmMtOGE0Ny00NWFlLTliNmUtNjY3ODExYjgxNmUyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'The Host', 'https://www.youtube.com/embed/1HRTy26s4hw', '2006'),
	(167, 'In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.', 'horror', 'tt0457430', 'https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNlZGZiYWI1YjMyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'Pan\'s Labyrinth', 'https://www.youtube.com/embed/jVZRnnVSQ8k', '2006'),
	(168, 'In the Iranian ghost-town Bad City, a place that reeks of death and loneliness, the townspeople are unaware they are being stalked by a lonesome vampire.', 'horror', 'tt2326554', 'https://m.media-amazon.com/images/M/MV5BMjMzNjMyMjU2M15BMl5BanBnXkFtZTgwMzA3NjQ0MzE@._V1_SX300.jpg', 'A Girl Walks Home Alone At Night', 'https://www.youtube.com/embed/_YGmTdo3vuY', '2014'),
	(169, 'A brilliant but eccentric scientist begins to transform into a giant man/fly hybrid after one of his experiments goes horribly wrong.', 'horror', 'tt0091064', 'https://m.media-amazon.com/images/M/MV5BODcxMGMwOGEtMDUxMi00MzE5LTg4YTYtYjk1YjA4MzQxNTNlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The Fly', 'https://www.youtube.com/embed/bdB02IufaW0', '1986'),
	(170, 'An American newcomer to a prestigious German ballet academy comes to realize that the school is a front for something sinister amid a series of grisly murders.', 'horror', 'tt0076786', 'https://m.media-amazon.com/images/M/MV5BMjRiYTNjODctNGU1Ni00NDg3LTk0NGUtMWU0NjgyZTAyYmNjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Suspiria', 'https://www.youtube.com/embed/5Y0EEqtWrJI', '1977'),
	(171, 'Five friends head out to rural Texas to visit the grave of a grandfather. On the way they stumble across what appears to be a deserted house, only to discover something sinister within. Something armed with a chainsaw.', 'horror', 'tt0072271', 'https://m.media-amazon.com/images/M/MV5BZDI3OWE0ZWMtNGJjOS00N2E4LWFiOTAtZjQ4OTNiNzIwN2NkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'The Texas Chain Saw Massacre', 'https://www.youtube.com/embed/T3TILW0O_C0', '1974'),
	(172, 'The enchanted lives of a couple in a secluded forest are brutally shattered by a nightmarish hippie cult and their demon-biker henchmen, propelling a man into a spiraling, surreal rampage of vengeance.', 'horror', 'tt6998518', 'https://m.media-amazon.com/images/M/MV5BMjk1MjhmZWQtNzU3OC00NDE4LThlODQtNTdhZGM4M2E3MWZkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Mandy', 'https://www.youtube.com/embed/rI054ow6KJk', '2018'),
	(173, 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy\'s room.', 'kids', 'tt0114709', 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg', 'Toy Story', 'https://www.youtube.com/embed/CxwTLktovTU', '1995'),
	(177, 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.', 'kids', 'tt2096673', 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg', 'Inside Out', 'https://www.youtube.com/embed/yRUAzGQ3nSY', '2015'),
	(178, '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.', 'kids', 'tt1049413', 'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg', 'UP', 'https://www.youtube.com/embed/HWEW_qTLSEE', '2009'),
	(179, 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 'kids', 'tt2380307', 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg', 'Coco', 'https://www.youtube.com/embed/zNCz4mQzfEI', '2017'),
	(180, 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.', 'kids', 'tt0083866', 'https://m.media-amazon.com/images/M/MV5BMTQ2ODFlMDAtNzdhOC00ZDYzLWE3YTMtNDU4ZGFmZmJmYTczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'E.T. the Extra-Terrestrial', 'https://www.youtube.com/embed/wZNInG8kSiA', '1982'),
	(181, 'Exiled into the dangerous forest by her wicked stepmother, a princess is rescued by seven dwarf miners who make her part of their household.', 'kids', 'tt0029583', 'https://m.media-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_SX300.jpg', 'Snow White and the Seven Dwarfs', 'https://www.youtube.com/embed/WKSd9-12cj4', '1937'),
	(182, 'After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.', 'kids', 'tt2948372', 'https://m.media-amazon.com/images/M/MV5BZGE1MDg5M2MtNTkyZS00MTY5LTg1YzUtZTlhZmM1Y2EwNmFmXkEyXkFqcGdeQXVyNjA3OTI0MDc@._V1_SX300.jpg', 'Soul', 'https://www.youtube.com/embed/xOsLIiBStEs', '2020'),
	(185, 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana\'s island, she answers the Ocean\'s call to seek out the Demigod to set things right.', 'kids', 'tt3521164', 'https://m.media-amazon.com/images/M/MV5BMjI4MzU5NTExNF5BMl5BanBnXkFtZTgwNzY1MTEwMDI@._V1_SX300.jpg', 'Moana', 'https://www.youtube.com/embed/LKFuXETZUsI', '2016'),
	(187, 'Ridiculed because of his enormous ears, a young circus elephant is assisted by a mouse to achieve his full potential.', 'kids', 'tt0033563', 'https://m.media-amazon.com/images/M/MV5BNWVmNWQ2OTQtNzJlNC00ZmQwLTg4ZTktZTNmM2IxZTlkOGM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'Dumbo', 'https://www.youtube.com/embed/8QgTNmlBxTE', '1941'),
	(188, 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.', 'kids', 'tt0382932', 'https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg', 'Ratatouille', 'https://www.youtube.com/embed/PeFGdSrFTUw', '2007'),
	(189, 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.', 'kids', 'tt0317705', 'https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg', 'The Incredibles', 'https://www.youtube.com/embed/-UaGUdNJdRQ', '2004'),
	(194, 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 'kids', 'tt0245429', 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Spirited Away', 'https://www.youtube.com/embed/AZL_zEeLg8o', '2002'),
	(195, 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'kids', 'tt0110357', 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg', 'The Lion King', 'https://www.youtube.com/embed/lFzVJEksoDY', '1994'),
	(196, 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.', 'kids', 'tt0129167', 'https://m.media-amazon.com/images/M/MV5BMjIxNDU2Njk0OV5BMl5BanBnXkFtZTgwODc3Njc3NjE@._V1_SX300.jpg', 'The Iron Giant', 'https://www.youtube.com/embed/fq2FZdvQXXg', '1999'),
	(198, 'A toon-hating detective is a cartoon rabbit\'s only hope to prove his innocence when he is accused of murder.', 'kids', 'tt0096438', 'https://m.media-amazon.com/images/M/MV5BMDhiOTM2OTctODk3Ny00NWI4LThhZDgtNGQ4NjRiYjFkZGQzXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg', 'Who Framed Roger Rabbit?', 'https://www.youtube.com/embed/gpDaNqSXxp0', '1988'),
	(199, 'A collection of animated interpretations of great works of Western classical music, ranging from the abstract to depictions of mythology and fantasy, and settings including the prehistoric, supernatural and sacred.', 'kids', 'tt0032455', 'https://m.media-amazon.com/images/M/MV5BMjAxMTI1Njk3OF5BMl5BanBnXkFtZTgwNjkzODk4NTE@._V1_SX300.jpg', 'Fantasia', 'https://www.youtube.com/embed/Q4S92yRzJa8', '1940'),
	(200, 'Babe, a pig raised by sheepdogs on a rural English farm, learns to herd sheep with a little help from Farmer Hoggett.', 'kids', 'tt0112431', 'https://m.media-amazon.com/images/M/MV5BYjg4ZjUzMzMtYzlmYi00YTcwLTlkOWUtYWFmY2RhNjliODQzXkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SX300.jpg', 'Babe', 'https://www.youtube.com/embed/Gch2Mm1wPEE', '1995'),
	(202, 'A young witch, on her mandatory year of independent life, finds fitting into a new community difficult while she supports herself by running an air courier service.', 'kids', 'tt0097814', 'https://m.media-amazon.com/images/M/MV5BOTc0ODM1Njk1NF5BMl5BanBnXkFtZTcwMDI5OTEyNw@@._V1_SX300.jpg', 'Kiki\'s Delivery Service', 'https://www.youtube.com/embed/CJRJveWPPRU', '1989'),
	(203, 'A young maiden in a land called Andalasia, who is prepared to be wed, is sent away to New York City by an evil Queen, where she falls in love with a lawyer.', 'kids', 'tt0461770', 'https://m.media-amazon.com/images/M/MV5BMjE4NDQ2Mjc0OF5BMl5BanBnXkFtZTcwNzQ2NDE1MQ@@._V1_SX300.jpg', 'Enchanted', 'https://www.youtube.com/embed/v_zVdE4sSos', '2007'),
	(204, 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.', 'kids', 'tt2294629', 'https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX300.jpg', 'Frozen', 'https://www.youtube.com/embed/TbQm5doF_Uc', '2013'),
	(205, 'A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.', 'kids', 'tt0103639', 'https://m.media-amazon.com/images/M/MV5BY2Q2NDI1MjUtM2Q5ZS00MTFlLWJiYWEtNTZmNjQ3OGJkZDgxXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg', 'Aladdin', 'https://www.youtube.com/embed/eTjHiQKJUDY', '1992'),
	(206, 'The story of a young deer growing up in the forest.', 'kids', 'tt0034492', 'https://m.media-amazon.com/images/M/MV5BY2JhMTJmYjYtNTVkYi00OWE3LWJlMjEtOWI4MTFkMjJhMmQ3XkEyXkFqcGdeQXVyNzY1NDgwNjQ@._V1_SX300.jpg', 'Bambi', 'https://www.youtube.com/embed/suAZVUatuH0', '1942'),
	(207, 'A mermaid princess makes a Faustian bargain in an attempt to become human and win a prince\'s love.', 'kids', 'tt0097757', 'https://m.media-amazon.com/images/M/MV5BN2JlZTBhYTEtZDE3OC00NTA3LTk5NTQtNjg5M2RjODllM2M0XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg', 'The Little Mermaid', 'https://www.youtube.com/embed/ZGZX5-PAwR8', '1989'),
	(209, 'On a journey to find the cure for a Tatarigami\'s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.', 'kids', 'tt0119698', 'https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_SX300.jpg', 'Princess Mononoke', 'https://www.youtube.com/embed/4OiMOHRDs14', '1999'),
	(210, 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.', 'kids', 'tt0096283', 'https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'My Neighbor Totoro', 'https://www.youtube.com/embed/WJC1qciW_3k', '1988'),
	(211, 'A misfit ant, looking for "warriors" to save his colony from greedy grasshoppers, recruits a group of bugs that turn out to be an inept circus troupe.', 'kids', 'tt0120623', 'https://m.media-amazon.com/images/M/MV5BNThmZGY4NzgtMTM4OC00NzNkLWEwNmEtMjdhMGY5YTc1NDE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'A Bug\'s Life', 'https://www.youtube.com/embed/mE35XQFxbeo', '1998'),
	(212, 'A poor but hopeful boy seeks one of the five coveted golden tickets that will send him on a tour of Willy Wonka\'s mysterious chocolate factory.', 'kids', 'tt0067992', 'https://m.media-amazon.com/images/M/MV5BZTllNDU0ZTItYTYxMC00OTI4LThlNDAtZjNiNzdhMWZiYjNmXkEyXkFqcGdeQXVyNzY1NDgwNjQ@._V1_SX300.jpg', 'Willy Wonka and the Chocolate Factory', 'https://www.youtube.com/embed/2WKPKnggJqk', '1971'),
	(213, 'A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.', 'kids', 'tt0126029', 'https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Shrek', 'https://www.youtube.com/embed/CwXOrWvPBPk', '2001'),
	(214, 'After being snubbed by the royal family, a malevolent fairy places a curse on a princess which only a prince can break, along with the help of three good fairies.', 'kids', 'tt0053285', 'https://m.media-amazon.com/images/M/MV5BOTJmZjA3MjMtMWNmZS00YTliLWFhMWUtZDU2NGJhNTlmY2ZkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Sleeping Beauty', 'https://www.youtube.com/embed/6kj1_2WUTtc', '1959'),
	(215, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', 'sci-fi', 'tt1392190', 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Mad Max: Fury Road', 'https://www.youtube.com/embed/hEJnMQG9ev8', '2015'),
	(219, 'In a time of conflict, a group of unlikely heroes band together on a mission to steal the plans to the Death Star, the Empire\'s ultimate weapon of destruction.', 'sci-fi', 'tt3748528', 'https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_SX300.jpg', 'Rogue One: A Star Wars Story', 'https://www.youtube.com/embed/frdj1zb9sMY', '2016'),
	(225, 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.', 'sci-fi', 'tt0076759', 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Star Wars', 'https://www.youtube.com/embed/XHk5kCIiGoM', '1977'),
	(226, 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.', 'sci-fi', 'tt2543164', 'https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg', 'Arrival', 'https://www.youtube.com/embed/tFMo3UJ4B4g', '2016'),
	(227, 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.', 'horror', 'tt0078748', 'https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Alien', 'https://www.youtube.com/embed/sVwH0hIvV5k', '1979'),
	(228, 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.', 'sci-fi', 'tt1856101', 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg', 'Blade Runner 2049', 'https://www.youtube.com/embed/gCcx85zbxz4', '2017'),
	(229, 'A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.', 'sci-fi', 'tt0083658', 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Blade Runner', 'https://www.youtube.com/embed/qoEyZoOTtss', '1982'),
	(231, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.', 'sci-fi', 'tt1798709', 'https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg', 'Her', 'https://www.youtube.com/embed/ne6p6MfLBxc', '2013'),
	(232, 'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity\'s future salvation.', 'action', 'tt0088247', 'https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The Terminator', NULL, '1984'),
	(233, 'In a future where a failed climate change experiment has killed all life except for the survivors who boarded the Snowpiercer (a train that travels around the globe), a new class system emerges.', 'sci-fi', 'tt1706620', 'https://m.media-amazon.com/images/M/MV5BMTQ3NzA1MTY3MV5BMl5BanBnXkFtZTgwNzE2Mzg5MTE@._V1_SX300.jpg', 'Snowpiercer', 'https://www.youtube.com/embed/nX5PwfEMBM0', '2014'),
	(234, 'A guide leads two men through an area known as the Zone to find a room that grants wishes.', 'weird', 'tt0079944', 'https://m.media-amazon.com/images/M/MV5BMDgwODNmMGItMDcwYi00OWZjLTgyZjAtMGYwMmI4N2Q0NmJmXkEyXkFqcGdeQXVyNzY1MTU0Njk@._V1_SX300.jpg', 'Stalker', NULL, '1979'),
	(235, 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.', 'sci-fi', 'tt0088763', 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Back to the Future', 'https://www.youtube.com/embed/C-4Pr9kBtGc', '1985'),
	(236, 'A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don\'t apply.', 'sci-fi', 'tt2798920', 'https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SX300.jpg', 'Annihilation', 'https://www.youtube.com/embed/89OP78l9oF0', '2018'),
	(237, 'An American grandson of the infamous scientist, struggling to prove that his grandfather was not as insane as people believe, is invited to Transylvania, where he discovers the process that reanimates a dead body.', 'comedy', 'tt0072431', 'https://m.media-amazon.com/images/M/MV5BMTEwNjg2MjM2ODFeQTJeQWpwZ15BbWU4MDQ1MDU5OTEx._V1_SX300.jpg', 'Young Frankenstein', 'https://www.youtube.com/embed/sO8g8VmFf0M', '1974'),
	(238, 'Astronaut Sam Bell has a quintessentially personal encounter toward the end of his three-year stint on the Moon, where he, working alongside his computer, GERTY, sends back to Earth parcels of a resource that has helped diminish our planet\'s power problem', 'sci-fi', 'tt1182345', 'https://m.media-amazon.com/images/M/MV5BMTgzODgyNTQwOV5BMl5BanBnXkFtZTcwNzc0NTc0Mg@@._V1_SX300.jpg', 'Moon', 'https://www.youtube.com/embed/twuScTcDP_Q', '2009'),
	(239, 'A robot malfunction creates havoc and terror for unsuspecting vacationers at a futuristic, adult-themed amusement park.', 'sci-fi', 'tt0070909', 'https://m.media-amazon.com/images/M/MV5BMWY0NzM5MDAtYTg2NC00MDZjLTgwM2UtZjdiOTEzMjQ4MjU0L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'Westworld', 'https://www.youtube.com/embed/EjyOfTEeNHA', '1973'),
	(240, 'A man struggles with memories of his past, which include a wife he cannot remember and a nightmarish world no one else ever seems to wake up from.', 'sci-fi', 'tt0118929', 'https://m.media-amazon.com/images/M/MV5BMGExOGExM2UtNWM5ZS00OWEzLTllNzYtM2NlMTJlYjBlZTJkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Dark City', 'https://www.youtube.com/embed/gt9HkO-cGGo', '1998'),
	(241, 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'sci-fi', 'tt0133093', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'The Matrix', 'https://www.youtube.com/embed/vKQi3bBA1y8', '1999'),
	(242, 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 'sci-fi', 'tt1375666', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'Inception', 'https://www.youtube.com/embed/GuW4X4Gwq2w', '2010'),
	(243, 'A cyborg policewoman and her partner hunt a mysterious and powerful hacker called the Puppet Master.', 'sci-fi', 'tt0113568', 'https://i.pinimg.com/originals/75/d1/57/75d157276e6ed51fbac6770ab54b98e7.jpg', 'Ghost in the Shell', 'https://www.youtube.com/embed/2uMNtOQOaLU', '1995'),
	(244, 'Violence ensues after an extraterrestrial race forced to live in slum-like conditions on Earth finds a kindred spirit in a government agent exposed to their biotechnology.', 'sci-fi', 'tt1136608', 'https://m.media-amazon.com/images/M/MV5BYmQ5MzFjYWMtMTMwNC00ZGU5LWI3YTQtYzhkMGExNGFlY2Q0XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg', 'District 9', 'https://www.youtube.com/embed/DyLUwOcR5pk', '2009'),
	(245, 'A man and woman are drawn together, entangled in the life cycle of an ageless organism. Identity becomes an illusion as they struggle to assemble the loose fragments of wrecked lives.', 'sci-fi', 'tt2084989', 'https://m.media-amazon.com/images/M/MV5BMTQzMzQ4MDAyNF5BMl5BanBnXkFtZTcwNzE0MDk3OA@@._V1_SX300.jpg', 'Upstream Color', 'https://www.youtube.com/embed/SilYsr_3vrA', '2012'),
	(246, 'A paranoid mathematician searches for a key number that will unlock the universal patterns found in nature.', 'thriller', 'tt0138704', 'https://m.media-amazon.com/images/M/MV5BMjYzNTA4YzItYTQ2Yy00NDQwLWI2OGItN2JmMjZhZTVhMzI5L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'Pi', 'https://www.youtube.com/embed/jo18VIoR2xU', '1998'),
	(247, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', 'sci-fi', 'tt0816692', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Interstellar', 'https://www.youtube.com/embed/2LqzF5WauAw', '2014'),
	(248, 'Ultimate L.A. slacker Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for a rug ruined by debt collectors, enlisting his bowling buddies for help while trying to find the millionaire\'s missing wife.', 'comedy', 'tt0118715', 'https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg', 'The Big Lebowski', 'https://www.youtube.com/embed/cd-go0oBF4Y', '1996'),
	(249, 'In an alternate present-day version of Oakland, telemarketer Cassius Green discovers a magical key to professional success, propelling him into a universe of greed.', 'comedy', 'tt5688932', 'https://m.media-amazon.com/images/M/MV5BNjgwMmI4YzUtZGI2Mi00M2MwLWIyMmMtZWYzMWZmNzAyNmYwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Sorry To Bother You', 'https://www.youtube.com/embed/enH3xA4mYcY', '2018'),
	(250, 'Moscow, 1953. After being in power for nearly thirty years, Soviet dictator Joseph Vissarionovich Stalin takes ill and quickly dies. Now the members of the Council of Ministers scramble for power.', 'comedy', 'tt4686844', 'https://m.media-amazon.com/images/M/MV5BMTcxMDc1NjcyNl5BMl5BanBnXkFtZTgwNDU0NDYxMzI@._V1_SX300.jpg', 'The Death of Stalin', 'https://www.youtube.com/embed/LiJ-0cjMD60', '2018'),
	(251, 'Viago, Deacon, and Vladislav are vampires who are struggling with the mundane aspects of modern life, like paying rent, keeping up with the chore wheel, trying to get into nightclubs, and overcoming flatmate conflicts.', 'comedy', 'tt3416742', 'https://m.media-amazon.com/images/M/MV5BMjAwNDA5NzEwM15BMl5BanBnXkFtZTgwMTA1MDUyNDE@._V1_SX300.jpg', 'What We Do in the Shadows', 'https://www.youtube.com/embed/IAZEWtyhpes', '2015'),
	(252, 'Three parapsychologists forced out of their university funding set up shop as a unique ghost removal service in New York City, attracting frightened yet skeptical customers.', 'comedy', 'tt0087332', 'https://m.media-amazon.com/images/M/MV5BMTkxMjYyNzgwMl5BMl5BanBnXkFtZTgwMTE3MjYyMTE@._V1_SX300.jpg', 'Ghostbusters', 'https://www.youtube.com/embed/wQAljlSmjC8', '1984'),
	(253, 'A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.', 'comedy', 'tt0335266', 'https://m.media-amazon.com/images/M/MV5BMTUxMzk0NDg1MV5BMl5BanBnXkFtZTgwNDg0NjkxMDI@._V1_SX300.jpg', 'Lost In Translation', 'https://www.youtube.com/embed/g_maEh38ZTw', '2003'),
	(254, 'A listless and alienated teenager decides to help his new friend win the class presidency in their small western high school, while he must deal with his bizarre family life back home.', 'comedy', 'tt0374900', 'https://m.media-amazon.com/images/M/MV5BNjYwNTA3MDIyMl5BMl5BanBnXkFtZTYwMjIxNjA3._V1_SX300.jpg', 'Napoleon Dynamite', 'https://www.youtube.com/embed/X6hAXAvh_o8', '2004'),
	(255, 'When a childless couple of an ex-con and an ex-cop decide to help themselves to one of another family\'s quintuplets, their lives become more complicated than they anticipated.', 'comedy', 'tt0093822', 'https://m.media-amazon.com/images/M/MV5BOGUwZTEwZTYtZmQ0OS00NmM1LWE2ZTQtNjZiYmE4ZmUxMjk1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Raising Arizona', 'https://www.youtube.com/embed/OjWu8i6eMZo', '1987'),
	(256, 'A Naval veteran arrives home from war unsettled and uncertain of his future - until he is tantalized by the Cause and its charismatic leader.', 'drama', 'tt1560747', 'https://m.media-amazon.com/images/M/MV5BMTQ2NjQ5MzMwMF5BMl5BanBnXkFtZTcwMjczNTAzOA@@._V1_SX300.jpg', 'The Master', 'https://www.youtube.com/embed/KATzhOep5r8', '2012'),
	(257, 'Self-proclaimed stuntman Rod Kimble is preparing for the jump of his life - to clear fifteen buses to raise money for his abusive stepfather Frank\'s life-saving heart operation.', 'comedy', 'tt0787475', 'https://m.media-amazon.com/images/M/MV5BNjYwNjA3OTY0Nl5BMl5BanBnXkFtZTcwNDMyNDUzMw@@._V1_SX300.jpg', 'Hot Rod', 'https://www.youtube.com/embed/gbu88CKkEzI', '2007'),
	(258, 'Spinal Tap, one of England\'s loudest bands, is chronicled by film director Marty DiBergi on what proves to be a fateful tour.', 'comedy', 'tt0088258', 'https://m.media-amazon.com/images/M/MV5BMTQ2MTIzMzg5Nl5BMl5BanBnXkFtZTgwOTc5NDI1MDE@._V1_SX300.jpg', 'This Is Spinal Tap', 'https://www.youtube.com/embed/z6F0VyKp4Ik', '1984'),
	(259, 'With a plan to exact revenge on a mythical shark that killed his partner, Oceanographer Steve Zissou rallies a crew that includes his estranged wife, a journalist, and a man who may or may not be his son.', 'comedy', 'tt0362270', 'https://m.media-amazon.com/images/M/MV5BMTYzODYzNzg2MF5BMl5BanBnXkFtZTcwMTkzOTQzMw@@._V1_SX300.jpg', 'The Life Aquatic with Steve Zissou', 'https://www.youtube.com/embed/UpU0DZXTGA0', '2004'),
	(260, 'The eccentric members of a dysfunctional family reluctantly gather under the same roof for various reasons.', 'comedy', 'tt0265666', 'https://m.media-amazon.com/images/M/MV5BYmUzODQ5MGItZTZlNy00MDBhLWIxMmItMjg4Y2QyNDFlMWQ2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'The Royal Tenenbaums', 'https://www.youtube.com/embed/-DNAI9bhBFU', '2001'),
	(261, 'The uneventful, aimless lives of a London electronics salesman and his layabout roommate are disrupted by the zombie apocalypse.', 'comedy', 'tt0365748', 'https://m.media-amazon.com/images/M/MV5BMTg5Mjk2NDMtZTk0Ny00YTQ0LWIzYWEtMWI5MGQ0Mjg1OTNkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Shaun of the Dead', 'https://www.youtube.com/embed/LIfcaZ4pC-4', '2004'),
	(262, 'Shallow, rich and socially successful Cher is at the top of her Beverly Hills high school\'s pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other.', 'comedy', 'tt0112697', 'https://m.media-amazon.com/images/M/MV5BMzBmOGQ0NWItOTZjZC00ZDAxLTgyOTEtODJiYWQ2YWNiYWVjXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg', 'Clueless', 'https://www.youtube.com/embed/-lpBN48aEnw', '1995'),
	(263, 'A behind-the-scenes look into the highly competitive and cut-throat world of dog shows through the eyes of a group of ruthless dog owners.', 'comedy', 'tt0218839', 'https://m.media-amazon.com/images/M/MV5BMTQ5OTc0NDU1MF5BMl5BanBnXkFtZTYwNzk1OTI3._V1_SX300.jpg', 'Best In Show', 'https://www.youtube.com/embed/94y9n9lNy2Y', '2000'),
	(264, 'Two slacker friends try to promote their public-access cable show.', 'comedy', 'tt0105793', 'https://m.media-amazon.com/images/M/MV5BMDAyNDY3MjUtYmJjYS00Zjc5LTlhM2MtNzgzYjNlOWVkZjkzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Wayne\'s World', 'https://www.youtube.com/embed/AFDmxX3V8Bc', '1992'),
	(265, 'A pretty, popular teenager can\'t go out on a date until her ill-tempered older sister does.', 'comedy', 'tt0147800', 'https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', '10 Things I Hate About You', 'https://www.youtube.com/embed/7KCk7SIqUZA', '1999'),
	(266, 'A high school wise guy is determined to have a day off from school, despite what the Principal thinks of that.', 'comedy', 'tt0091042', 'https://m.media-amazon.com/images/M/MV5BMDA0NjZhZWUtNmI2NC00MmFjLTgwZDYtYzVjZmNhMDVmOTBkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Ferris Bueller\'s Day Off', 'https://www.youtube.com/embed/0ZDbKhkLxTs', '1986'),
	(267, 'A skilled London police officer, after irritating superiors with his embarrassing effectiveness, is transferred to a village where the easygoing officers object to his fervor for regulations, as a string of grisly murders strikes the town.', 'comedy', NULL, 'https://m.media-amazon.com/images/M/MV5BMzg4MDJhMDMtYmJiMS00ZDZmLThmZWUtYTMwZDM1YTc5MWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Hot Fuzz', 'https://www.youtube.com/embed/zAYRhk9b8a8', '2007'),
	(268, 'After a bitter divorce, an actor disguises himself as a female housekeeper to spend time with his children held in custody by his former wife.', 'comedy', 'tt0107614', 'https://m.media-amazon.com/images/M/MV5BMjExMDUzODE1N15BMl5BanBnXkFtZTgwNTU5NTYxMTE@._V1_SX300.jpg', 'Mrs. Doubtfire', 'https://www.youtube.com/embed/G1yg0T3xoS4', '1993'),
	(269, 'Steven, a charismatic surgeon, is forced to make an unthinkable sacrifice after his life starts to fall apart, when the behavior of a teenage boy he has taken under his wing turns sinister.', 'thriller', 'tt5715874', 'https://m.media-amazon.com/images/M/MV5BMjU4NDcwOTA2NF5BMl5BanBnXkFtZTgwMjE2OTg4MzI@._V1_SX300.jpg', 'The Killing of a Sacred Deer', 'https://www.youtube.com/embed/CQFdGfwChtw', '2017'),
	(270, 'A wealthy art gallery owner is haunted by her ex-husband\'s novel, a violent thriller she interprets as a symbolic revenge tale.', 'thriller', 'tt4550098', 'https://m.media-amazon.com/images/M/MV5BMTYwMzMwMzgxNl5BMl5BanBnXkFtZTgwMTA0MTUzMDI@._V1_SX300.jpg', 'Nocturnal Animals', 'https://www.youtube.com/embed/juFmTNbFh8g', '2016'),
	(271, 'When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story.', 'thriller', 'tt2872718', 'https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg18', 'Nightcrawler', 'https://www.youtube.com/embed/Ah9KiBp7BqA', '2014'),
	(272, 'A young woman is held in an underground bunker by a man who insists that a hostile event has left the surface of the Earth uninhabitable.', 'thriller', 'tt1179933', 'https://m.media-amazon.com/images/M/MV5BMjEzMjczOTIxMV5BMl5BanBnXkFtZTgwOTUwMjI3NzE@._V1_SX300.jpg', '10 Cloverfield Lane', 'https://www.youtube.com/embed/1WQfDnj_e2I', '2016'),
	(273, 'After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.', 'thriller', 'tt0166924', 'https://m.media-amazon.com/images/M/MV5BNWM5MWY2ZjItNDY1NC00MzQ3LWFiOGUtYzE2MTI4ZTk1ZTVkXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_SX300.jpg', 'Mulholland Drive', 'https://www.youtube.com/embed/3oa64ktrwKY', '2001'),
	(274, 'Laura Palmer\'s harrowing final days are chronicled one year after the murder of Teresa Banks, a resident of Twin Peaks\' neighboring town.', 'thriller', 'tt0105665', 'https://m.media-amazon.com/images/M/MV5BMzc5ODcyNTYtMDAwNy00MDhjLWFmOWUtNGVhMDRlYjE1YzNjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Twin Peaks: Fire Walk with Me', 'https://www.youtube.com/embed/5qQauPG61ZI', '1992'),
	(275, 'A lonely woman befriends a group of teenagers and decides to let them party at her house. Just when the kids think their luck couldn\'t get any better, things start happening that make them question the intention of their host.', 'thriller', 'tt7958736', 'https://m.media-amazon.com/images/M/MV5BMTA2MjA3ODU0NjBeQTJeQWpwZ15BbWU4MDE3NTQxNDcz._V1_SX300.jpg', 'Ma', 'https://www.youtube.com/embed/eIvbEC8N3cA', '2019'),
	(276, 'A couple\'s relationship is tested when uninvited guests arrive at their home, disrupting their tranquil existence.', 'thriller', 'tt5109784', 'https://m.media-amazon.com/images/M/MV5BMzc5ODExODE0MV5BMl5BanBnXkFtZTgwNDkzNDUxMzI@._V1_SX300.jpg', 'Mother!', 'https://www.youtube.com/embed/XpICoc65uh0', '2017'),
	(277, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.', 'thriller', 'tt2267998', 'https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg', 'Gone Girl', 'https://www.youtube.com/embed/2-_-1nJf8Vg', '2014'),
	(278, 'Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.', 'thriller', 'tt3170832', 'https://m.media-amazon.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_SX300.jpg', 'Room', 'https://www.youtube.com/embed/E_Ci-pAL4eE', '2015'),
	(279, 'In New York City 1981, an ambitious immigrant fights to protect his business and family during the most dangerous year in the city\'s history.', 'thriller', 'tt2937898', 'https://m.media-amazon.com/images/M/MV5BMjE4OTY4ODg3Ml5BMl5BanBnXkFtZTgwMTI1MTg1MzE@._V1_SX300.jpg', 'A Most Violent Year', 'https://www.youtube.com/embed/ySWXwXlXlQU', '2014'),
	(280, 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.', 'thriller', 'tt0477348', 'https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg', 'No Country for Old Men', 'https://www.youtube.com/embed/A0oNrgumrlE', '2007'),
	(281, 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 'thriller', 'tt0102926', 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'The Silence of the Lambs', 'https://www.youtube.com/embed/W6Mm8Sbe__o', '1991'),
	(282, 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.', 'thriller', 'tt0081505', 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'The Shining', 'https://www.youtube.com/embed/S014oGZiSdI', '1980'),
	(283, 'The lives of three men who were childhood friends are shattered when one of them has a family tragedy.', 'thriller', 'tt0327056', 'https://m.media-amazon.com/images/M/MV5BMTIzNDUyMjA4MV5BMl5BanBnXkFtZTYwNDc4ODM3._V1_SX300.jpg', 'Mystic River', 'https://www.youtube.com/embed/W7NktJhrRYQ', '2003'),
	(284, 'An epic mosaic of interrelated characters in search of love, forgiveness, and meaning in the San Fernando Valley.', 'drama', 'tt0175880', 'https://m.media-amazon.com/images/M/MV5BZjk3YThkNDktNjZjMS00MTBiLTllNTAtYzkzMTU0N2QwYjJjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Magnolia', 'https://www.youtube.com/embed/-2iaHK-MO9M', '1999'),
	(285, 'Set over one summer, the film follows precocious six-year-old Moonee as she courts mischief and adventure with her ragtag playmates and bonds with her rebellious but caring mother, all while living in the shadows of Walt Disney World.', 'drama', 'tt5649144', 'https://m.media-amazon.com/images/M/MV5BMjg4ZmY1MmItMjFjOS00ZTg2LWJjNDYtNDM2YmM2NzhiNmZhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg', 'The Florida Project', 'https://www.youtube.com/embed/WwQ-NH1rRT4', '2017'),
	(286, 'Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.', 'drama', 'tt10293406', 'https://m.media-amazon.com/images/M/MV5BZGRhYjE2NWUtN2FkNy00NGI3LTkxYWMtMDk4Yjg5ZjI3MWI2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg', 'The Power of the Dog', 'https://www.youtube.com/embed/LRDPo0CHrko', '2021'),
	(287, 'Robert Ford, who\'s idolized Jesse James since childhood, tries hard to join the reforming gang of the Missouri outlaw, but gradually becomes resentful of the bandit leader.', 'drama', 'tt0443680', 'https://m.media-amazon.com/images/M/MV5BMTY2NDI2MTc2NV5BMl5BanBnXkFtZTcwNjA2NTQzMw@@._V1_SX300.jpg', 'The Assassination of Jesse James by the Coward Rob', 'https://www.youtube.com/embed/6RwAWZtK5Uw', '0000'),
	(288, 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.', 'drama', 'tt0317248', 'https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'City of God', 'https://www.youtube.com/embed/RfnGQetbX-U', '2002'),
	(289, 'Minnesota car salesman Jerry Lundegaard\'s inept crime falls apart due to his and his henchmen\'s bungling and the persistent police work of the quite pregnant Marge Gunderson.', 'drama', 'tt0116282', 'https://m.media-amazon.com/images/M/MV5BNDJiZDgyZjctYmRjMS00ZjdkLTkwMTEtNGU1NDg3NDQ0Yzk1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Fargo', 'https://www.youtube.com/embed/ju75Sd4yAZw', '1996'),
	(290, 'In 2027, in a chaotic world in which women have become somehow infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.', 'drama', 'tt0206634', 'https://m.media-amazon.com/images/M/MV5BMTQ5NTI2NTI4NF5BMl5BanBnXkFtZTcwNjk2NDA2OQ@@._V1_SX300.jpg', 'Children of Men', 'https://www.youtube.com/embed/2VT2apoX90o', '2006'),
	(291, 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', 'drama', NULL, 'https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Requiem for a Dream', 'https://www.youtube.com/embed/WvfUkvl51t8', '2000'),
	(292, 'A delusional young man strikes up an unconventional relationship with a doll he finds on the Internet.', 'romance', 'tt0805564', 'https://m.media-amazon.com/images/M/MV5BMTI4NDc1NDkwMV5BMl5BanBnXkFtZTcwNjgzMDE1MQ@@._V1_SX300.jpg', 'Lars and the Real Girl', 'https://www.youtube.com/embed/XNcs9DrKYRU', '2002'),
	(293, 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice?', 'romance', 'tt0414387', 'https://m.media-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1_SX300.jpg', 'Pride & Prejudice', 'https://www.youtube.com/embed/Ur_DIHs92NM', '2005'),
	(294, 'Socially frustrated Barry Egan calls a phone-sex line to curb his loneliness. Little does he know it will land him in deep trouble and will jeopardize his burgeoning romance with the mysterious Lena.', 'romance', 'tt0272338', 'https://m.media-amazon.com/images/M/MV5BYmE1OTY4NjgtYjcwNC00NWE4LWJiNGMtZmVhYTdlMWE1YzIxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Punch-Drunk Love', 'https://www.youtube.com/embed/Nqv_gYTVSUo', '2002'),
	(295, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 'romance', 'tt3783958', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg', 'La La Land', 'https://www.youtube.com/embed/0pdqf4P9MB8', '2016'),
	(296, 'A poor Bohemian poet in 1890s Paris falls for a beautiful courtesan and nightclub star whom a jealous duke covets.', 'romance', 'tt0203009', 'https://m.media-amazon.com/images/M/MV5BMWFhYjliNjYtYjNhNS00OGExLWFhMjQtNDgwOWYyNWJiYzhmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Moulin Rouge!', 'https://www.youtube.com/embed/SyZDaTZSFuo', '2001'),
	(297, 'A man in a legal but hurtful business needs an escort for some social events, and hires a beautiful prostitute he meets... only to fall in love.', 'romance', 'tt0100405', 'https://m.media-amazon.com/images/M/MV5BNjk2ODQzNDYxNV5BMl5BanBnXkFtZTgwMTcyNDg4NjE@._V1_SX300.jpg', 'Pretty Woman', 'https://www.youtube.com/embed/2EBAVoN8L_U', '1990'),
	(298, 'In a dystopian near future, single people, according to the laws of The City, are taken to The Hotel, where they are obliged to find a romantic partner in forty-five days or are transformed into beasts and sent off into The Woods.', 'romance', 'tt3464902', 'https://m.media-amazon.com/images/M/MV5BNDQ1NDE5NzQ1NF5BMl5BanBnXkFtZTgwNzA5OTM2NTE@._V1_SX300.jpg', 'The Lobster', 'https://www.youtube.com/embed/LTNZmOJxuAc', '2015'),
	(299, 'As a modern-day scientist, Tommy is struggling with mortality, desperately searching for the medical breakthrough that will save the life of his cancer-stricken wife, Izzi.', 'romance', 'tt0414993', 'https://m.media-amazon.com/images/M/MV5BMTU5OTczMTcxMV5BMl5BanBnXkFtZTcwNDg3MTEzMw@@._V1_SX300.jpg', 'The Fountain', 'https://www.youtube.com/embed/GXkc4RzcBbQ', '2006'),
	(300, 'Oskar, an overlooked and bullied boy, finds love and revenge through Eli, a beautiful but peculiar girl.', 'romance', 'tt1139797', 'https://m.media-amazon.com/images/M/MV5BOWM4NTY2NTMtZDZlZS00NTgyLWEzZDMtODE3ZGI1MzI3ZmU5XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_SX300.jpg', 'Let the Right One In', 'https://www.youtube.com/embed/R0LYScpd-Lc', '2008'),
	(301, 'A noble underachiever and a beautiful valedictorian fall in love the summer before she goes off to college.', 'romance', 'tt0098258', 'https://m.media-amazon.com/images/M/MV5BMTg5OTk1NjczNl5BMl5BanBnXkFtZTgwNTE3NjkzMTE@._V1_SX300.jpg', 'Say Anything', 'https://www.youtube.com/embed/Se_eSeEAoX0', '1989'),
	(302, 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.', 'romance', 'tt0332280', 'https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_SX300.jpg', 'The Notebook', 'https://www.youtube.com/embed/BjJcYdEOI0k', '2004'),
	(303, 'A mousy governess who softens the heart of her employer soon discovers that he\'s hiding a terrible secret.', 'romance', 'tt1229822', 'https://m.media-amazon.com/images/M/MV5BNjU0Mjc0NzU3NF5BMl5BanBnXkFtZTcwMTU4OTkwNA@@._V1_SX300.jpg', 'Jane Eyre', 'https://www.youtube.com/embed/s1vSb318d74', '2011'),
	(304, 'Ennis and Jack are two shepherds who develop an emotional relationship. Their relationship becomes complicated when both of them get married to their respective girlfriends.', 'romance', 'tt0388795', 'https://m.media-amazon.com/images/M/MV5BMTY5NTAzNTc1NF5BMl5BanBnXkFtZTYwNDY4MDc3._V1_SX300.jpg', 'Brokeback Mountain', 'https://www.youtube.com/embed/U5D1iU5KnqQ', '2005'),
	(305, 'The world\'s greatest ever playwright, William Shakespeare, is young, out of ideas and short of cash, but meets his ideal woman and is inspired to write one of his most famous plays.', 'romance', 'tt0138097', 'https://m.media-amazon.com/images/M/MV5BM2ZkNjM5MjEtNTBlMC00OTI5LTgyYmEtZDljMzNmNzhiNzY0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'Shakespeare in Love', 'https://www.youtube.com/embed/v5R5La5f3eo', '1998'),
	(306, 'The Brothers Grimm arrive at the home of a wealthy Grande Dame who speaks of the many legends surrounding the fable of the cinder girl before telling the "true" story of her ancestor.', 'romance', 'tt0120631', 'https://m.media-amazon.com/images/M/MV5BN2FhYTY5ODItOGU4OC00MTkyLTlmYTMtYjIxN2Y4MmVlMDVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Ever After: A Cinderella Story', 'https://www.youtube.com/embed/szP9U0uLl5U', '1998'),
	(307, 'A poor girl must choose between the affections of dating her childhood sweetheart or a rich but sensitive playboy.', 'romance', 'tt0091790', 'https://m.media-amazon.com/images/M/MV5BOGE3ZmVjMzMtMDcxNi00YjM5LTg3NjMtZWMxYjlhNTk2MmZjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Pretty in Pink', 'https://www.youtube.com/embed/mRLQUGq8eE8', '1986'),
	(308, 'A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers.', 'kids', 'tt2953050', 'https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NzM0LTkwOTYtMDI4MmNkMzIxODhkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg', 'Encanto', 'https://www.youtube.com/embed/CaimKeDcudo', '2021'),
	(309, 'When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.', 'drama', 'tt1877830', 'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg', 'The Batman', 'https://www.youtube.com/embed/mqqft2x_Aa4', '2022'),
	(310, 'After unearthing a gem that controls an evil monster looking to destroy the Universe, a young girl and her brother use it to make him do their bidding.', 'comedy', 'tt11252440', 'https://m.media-amazon.com/images/M/MV5BOWNiMDUwYmUtZjJjNy00OTA5LThkM2QtODBkNTY2MGYyZGRlXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg', 'PG: Psycho Goreman', 'https://www.youtube.com/embed/L4tizc0IAVQ', '2020'),
	(311, 'A man in his thirties travels to a remote cabin to reconnect with his estranged father.', 'comedy', 'tt8816194', 'https://m.media-amazon.com/images/M/MV5BMmMxNGVjZWQtNzc4NC00MzBkLTgzODItNWQzN2UzNWY0Zjc4XkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg', 'Come To Daddy', 'https://www.youtube.com/embed/3D05YjZmVSI', '2019'),
	(312, 'A family in 1630s New England is torn apart by the forces of witchcraft, black magic, and possession.', 'horror', 'tt4263482', 'https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_SX300.jpg', 'The Witch', 'https://www.youtube.com/embed/iQXmlf3Sefg', '2015'),
	(313, 'In early 18th-century England, the status quo at the court is upset when a new servant arrives and endears herself to a frail Queen Anne.', 'drama', 'tt5083738', 'https://m.media-amazon.com/images/M/MV5BMTg1NzQwMDQxNV5BMl5BanBnXkFtZTgwNDg2NDYyNjM@._V1_SX300.jpg', 'The Favourite', 'https://www.youtube.com/embed/SYb-wkehT1g', '2018'),
	(314, 'An aspiring director and the marginally talented amateur cast of a hokey small-town Missouri musical production go overboard when they learn that someone from Broadway will be in attendance.', 'comedy', 'tt0118111', 'https://m.media-amazon.com/images/M/MV5BYWY4OGVjOTctYTViZC00MWQzLWIyNjYtM2JmOWIzZGQwNWYyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Waiting for Guffman', 'https://www.youtube.com/embed/s0Ml4u3hLlY', '1996');
/*!40000 ALTER TABLE `moviedata` ENABLE KEYS */;

-- Dumping structure for table vu2.role
CREATE TABLE IF NOT EXISTS `role` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.role: ~1 rows (approximately)
/*!40000 ALTER TABLE `role` DISABLE KEYS */;
INSERT INTO `role` (`id`, `name`) VALUES
	(1, 'ROLE_USER'),
	(2, 'ROLE_USER'),
	(3, 'ROLE_USER'),
	(4, 'ROLE_USER'),
	(5, 'ROLE_USER');
/*!40000 ALTER TABLE `role` ENABLE KEYS */;

-- Dumping structure for table vu2.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `first_name` varchar(30) NOT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.user: ~1 rows (approximately)
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` (`id`, `email`, `first_name`, `last_name`, `password`) VALUES
	(5, 'liz.gunther@gmail.com', 'Elizabeth', 'Gunther', '$2a$10$X12UxJrxGPmrzCjSMtKfBOLgmc7xJfLjkA0N.n3/LqnRwybMsFS3S');
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

-- Dumping structure for table vu2.users_roles
CREATE TABLE IF NOT EXISTS `users_roles` (
  `user_id` bigint(20) NOT NULL,
  `role_id` bigint(20) NOT NULL,
  KEY `FKt4v0rrweyk393bdgt107vdx0x` (`role_id`),
  KEY `FKgd3iendaoyh04b95ykqise6qh` (`user_id`),
  CONSTRAINT `FKgd3iendaoyh04b95ykqise6qh` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FKt4v0rrweyk393bdgt107vdx0x` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.users_roles: ~1 rows (approximately)
/*!40000 ALTER TABLE `users_roles` DISABLE KEYS */;
INSERT INTO `users_roles` (`user_id`, `role_id`) VALUES
	(5, 5);
/*!40000 ALTER TABLE `users_roles` ENABLE KEYS */;

-- Dumping structure for table vu2.wishlist
CREATE TABLE IF NOT EXISTS `wishlist` (
  `id` bigint(20) NOT NULL,
  `wishlist_name` varchar(255) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKd4r80jm8s41fgoa0xv9yy5lo8` (`user_id`),
  CONSTRAINT `FKd4r80jm8s41fgoa0xv9yy5lo8` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.wishlist: ~0 rows (approximately)
/*!40000 ALTER TABLE `wishlist` DISABLE KEYS */;
INSERT INTO `wishlist` (`id`, `wishlist_name`, `user_id`) VALUES
	(6, 'Rainy Day Wishlist', 5),
	(8, 'Rainy Day Wishlist', NULL);
/*!40000 ALTER TABLE `wishlist` ENABLE KEYS */;

-- Dumping structure for table vu2.wishlist_movie
CREATE TABLE IF NOT EXISTS `wishlist_movie` (
  `wishlist_id` bigint(20) NOT NULL,
  `movie_id` bigint(20) NOT NULL,
  PRIMARY KEY (`wishlist_id`,`movie_id`),
  KEY `FK9fjy58rq4houscg0a323pwit7` (`movie_id`),
  CONSTRAINT `FK9fjy58rq4houscg0a323pwit7` FOREIGN KEY (`movie_id`) REFERENCES `moviedata` (`id`),
  CONSTRAINT `FKbnu25m2aifumwir88fc5l41sj` FOREIGN KEY (`wishlist_id`) REFERENCES `wishlist` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table vu2.wishlist_movie: ~0 rows (approximately)
/*!40000 ALTER TABLE `wishlist_movie` DISABLE KEYS */;
/*!40000 ALTER TABLE `wishlist_movie` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
